# Generated by Django 5.1.6 on 2025-03-21 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_player_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=50)),
                ('score', models.IntegerField()),
                ('test_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
