# Generated by Django 5.1.4 on 2025-04-03 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_memorytestresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='MemoryTestResult',
        ),
        migrations.RemoveField(
            model_name='score',
            name='player',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='attempts',
            new_name='module',
        ),
        migrations.AddField(
            model_name='score',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
