# Generated by Django 5.1.4 on 2025-04-03 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_delete_memorytestresult_remove_score_player_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='module',
            field=models.CharField(max_length=100),
        ),
    ]
