# Generated by Django 5.1.6 on 2025-05-19 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_score_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='percentage',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
